# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: streaming.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'streaming.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstreaming.proto\x12\nfilestream\" \n\x0b\x46ileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x1a\n\tFileChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x32\x96\x01\n\x14\x46ileStreamingService\x12>\n\nStreamFile\x12\x17.filestream.FileRequest\x1a\x15.filestream.FileChunk0\x01\x12>\n\nUploadFile\x12\x15.filestream.FileChunk\x1a\x17.filestream.FileRequest(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'streaming_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREQUEST']._serialized_start=31
  _globals['_FILEREQUEST']._serialized_end=63
  _globals['_FILECHUNK']._serialized_start=65
  _globals['_FILECHUNK']._serialized_end=91
  _globals['_FILESTREAMINGSERVICE']._serialized_start=94
  _globals['_FILESTREAMINGSERVICE']._serialized_end=244
# @@protoc_insertion_point(module_scope)
